spring:
  datasource:
    url: jdbc:h2:./appdb
    username: sa
    password: admin

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8040